# Generated by Django 4.2.1 on 2024-02-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x75_m100', '0002_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='x75',
            name='date_on_excel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='x75',
            name='lot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='x75',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
