# Generated by Django 4.2.1 on 2024-02-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x75_m100', '0004_category_gio_luu_du_lieu_category_ngay_san_xuat'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_lddk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slsx', models.IntegerField(blank=True, null=True)),
                ('slpp', models.IntegerField(blank=True, null=True)),
                ('qc_choi', models.IntegerField(blank=True, null=True)),
                ('ng_choi', models.IntegerField(blank=True, null=True)),
                ('nham_choi', models.IntegerField(blank=True, null=True)),
                ('qc_chau', models.IntegerField(blank=True, null=True)),
                ('ng_chau', models.IntegerField(blank=True, null=True)),
                ('nham_chau', models.IntegerField(blank=True, null=True)),
                ('qc_bc_choi', models.IntegerField(blank=True, null=True)),
                ('ng_bc_choi', models.IntegerField(blank=True, null=True)),
                ('nham_bc_choi', models.IntegerField(blank=True, null=True)),
                ('qc_bc_chau', models.IntegerField(blank=True, null=True)),
                ('ng_bc_chau', models.IntegerField(blank=True, null=True)),
                ('nham_bc_chau', models.IntegerField(blank=True, null=True)),
                ('qc_pp_khac', models.IntegerField(blank=True, null=True)),
                ('ng_pp_khac', models.IntegerField(blank=True, null=True)),
                ('nham_pp_khac', models.IntegerField(blank=True, null=True)),
                ('tong_pp_qc', models.IntegerField(blank=True, null=True)),
                ('tong_pp_cong_doan', models.IntegerField(blank=True, null=True)),
                ('tong_pp_pdn', models.IntegerField(blank=True, null=True)),
                ('luu_xuat', models.IntegerField(blank=True, null=True)),
                ('luu_xuat_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('note', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='x75_m100.x75')),
            ],
        ),
    ]
