# Generated by Django 4.2.1 on 2024-02-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x75_m100', '0005_category_lddk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_lddk',
            name='luu_xuat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='ng_bc_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='ng_bc_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='ng_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='ng_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='ng_pp_khac',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='nham_bc_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='nham_bc_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='nham_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='nham_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='nham_pp_khac',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='qc_bc_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='qc_bc_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='qc_chau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='qc_choi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='qc_pp_khac',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='slpp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='slsx',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='tong_pp_cong_doan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='tong_pp_pdn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category_lddk',
            name='tong_pp_qc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
