# Generated by Django 4.2.1 on 2024-04-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0005_alter_server_test_host_alter_server_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAM_SAT_A75_M100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_on_excel', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('total_operate_time', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.server_test')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_san_xuat', models.CharField(blank=True, max_length=255, null=True)),
                ('gio_luu_du_lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('tong_so_luong_sx', models.IntegerField(blank=True, null=True)),
                ('keo_dinh_truc', models.IntegerField(blank=True, null=True)),
                ('keo_it_keo_khong_deu', models.IntegerField(blank=True, null=True)),
                ('keo_bi_thung_lo', models.IntegerField(blank=True, null=True)),
                ('keo_dinh_ban_comi', models.IntegerField(blank=True, null=True)),
                ('phe_pham_khac', models.IntegerField(blank=True, null=True)),
                ('tong_so_luong_pp', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tam_Sat_M100_A75.tam_sat_a75_m100')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
