# Generated by Django 4.2.1 on 2024-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tam_Sat_M100_A75', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keo_bi_thung_lo',
            new_name='keo_bi_thung_lo_cam_1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='keo_dinh_ban_comi',
            new_name='keo_bi_thung_lo_cam_2',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='keo_dinh_truc',
            new_name='keo_dinh_ban_comi_cam_1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='keo_it_keo_khong_deu',
            new_name='keo_dinh_ban_comi_cam_2',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='phe_pham_khac',
            new_name='keo_dinh_truc_cam_1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tong_so_luong_pp',
            new_name='keo_dinh_truc_cam_2',
        ),
        migrations.AddField(
            model_name='category',
            name='keo_it_keo_khong_deu_cam_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='keo_it_keo_khong_deu_cam_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='phe_pham_khac_cam_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='phe_pham_khac_cam_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tong_so_luong_pp_cam_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tong_so_luong_pp_cam_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
