# Generated by Django 4.2.1 on 2024-03-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0003_server_test_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='A18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_on_excel', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('total_operate_time', models.TimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.server_test')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_san_xuat', models.CharField(blank=True, max_length=255, null=True)),
                ('gio_luu_du_lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('tong_so_luong_sx', models.IntegerField(blank=True, null=True)),
                ('cuon_cam', models.IntegerField(blank=True, null=True)),
                ('cacbon_tay_choi', models.IntegerField(blank=True, null=True)),
                ('han_choi', models.IntegerField(blank=True, null=True)),
                ('han_chau', models.IntegerField(blank=True, null=True)),
                ('de_vo_nho', models.IntegerField(blank=True, null=True)),
                ('tu_dien', models.IntegerField(blank=True, null=True)),
                ('cong_chau_dien', models.IntegerField(blank=True, null=True)),
                ('bui_chi', models.IntegerField(blank=True, null=True)),
                ('phe_pham_khac', models.IntegerField(blank=True, null=True)),
                ('tong_so_luong_pp', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='A18_RS656.a18')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
