# Generated by Django 4.2.1 on 2024-03-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A18_RS656', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a18',
            name='total_operate_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
