# Generated by Django 4.2.1 on 2024-02-17 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_alter_server_test_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_on_excel', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.server_test')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_san_xuat', models.CharField(blank=True, max_length=255, null=True)),
                ('gio_luu_du_lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('tong_sl_sx', models.IntegerField(blank=True, null=True)),
                ('tong_sl_pp_kx', models.IntegerField(blank=True, null=True)),
                ('tay_choi', models.IntegerField(blank=True, null=True)),
                ('chau_dien', models.IntegerField(blank=True, null=True)),
                ('buichi', models.IntegerField(blank=True, null=True)),
                ('divat', models.IntegerField(blank=True, null=True)),
                ('cacbon', models.IntegerField(blank=True, null=True)),
                ('me_de', models.IntegerField(blank=True, null=True)),
                ('pp_khac', models.IntegerField(blank=True, null=True)),
                ('ty_le_pdn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('luu_xuat', models.IntegerField(blank=True, null=True)),
                ('luu_xuat_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='A1_RS446.a1')),
            ],
        ),
    ]
