# Generated by Django 4.2.1 on 2024-02-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, max_length=5, null=True)),
                ('host', models.GenericIPAddressField()),
                ('status', models.BooleanField(default=True)),
                ('folder_path', models.CharField(max_length=255)),
            ],
        ),
    ]
