# Generated by Django 4.2.1 on 2024-02-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_test_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_test',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
