# Generated by Django 4.2.1 on 2024-03-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_test_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_test',
            name='folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
