# Generated by Django 4.2.1 on 2024-03-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_server_test_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_test',
            name='host',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server_test',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
